### PR TITLE
Add warnings to Jobs

### PR DESCRIPTION
**Pull request by kirederik**
Document how warnings can be exposed on async operations

Co-authored-by: Joao Lebre <jlebre@pivotal.io>

### CODE REVIEW

**Comment by blgm** [comment]
@Gerg would you mind taking a look at this?

**Comment by tcdowney** [comment]
@kirederik @blgm can you add more context to the PR with respect to the use-case this is helping solve to provide some context? Are you wanting this to surface warnings from async service broker interactions?

Actually is this already existing behavior and you're just documenting it -- I think the PR and commit titles threw me off.

**Comment by reidmit** [comment]
It would be great to document what it looks like if there are no warnings. Is `warnings` an empty array? Or `null`? Or is the field left out?

I also wonder if there's a need for more than a `detail` field on the warning object. We're soon going to explore how we might leverage the `code` field on error objects better, so clients could distinguish between "types" of errors without string-matching on the `detail` text. Could there be a similar need for warnings?

**Comment by waterlink** [comment]
> Are you wanting this to surface warnings from async service broker interactions?

That’s right!

**Comment by waterlink** [comment]
> It would be great to document what it looks like if there are no warnings. Is warnings an empty array? Or null? Or is the field left out?

It’s going to be an empty warning array, and we’ll push another commit to document that.

**Comment by waterlink** [comment]
> I also wonder if there's a need for more than a detail field on the warning object. We're soon going to explore how we might leverage the code field on error objects better, so clients could distinguish between "types" of errors without string-matching on the detail text. Could there be a similar need for warnings?

We don’t see a need for that yet, because the warnings so far are only being rendered as is, for users. There is not really a decision that can be made on them right now, because they are not failures.

If there will be a use case for a code like that in the future, we can extend it then.

**Comment by waterlink** [comment]
So, TODO:
- [x] Add `warnings` field as empty array when there are no warnings.

**Comment by waterlink** [comment]
Hey @reid47 

We have applied your suggestion, and see more replies above to your questions. Could you take another look?

**Comment by selzoc** [comment]
So essentially this is a peer to the `errors` array that already exists on jobs? http://v3-apidocs.cloudfoundry.org/version/3.77.0/index.html#the-job-object

**Review by reidmit — APPROVED** [review]

**Review by selzoc — APPROVED** [review]

**Comment by kirederik** [comment]
> So essentially this is a peer to the `errors` array that already exists on jobs? http://v3-apidocs.cloudfoundry.org/version/3.77.0/index.html#the-job-object

Yes

**Comment by kirederik** [comment]
@ssisil @Gerg @tcdowney let us know if there's anything else you'd like clarification on.

**Pull request merged**
